[package]
name = "chat_client"
version = "0.1.0"
edition = "2024"
authors = ["Krickij LÃ¡szlo <krickijlaszlo@gmail.com>"]
description = """
Chat client
"""

[lints]
workspace = true

[dependencies]
chat_lib = { path = "../chat_lib", features = ["ratatui_span"] }

crossterm = "0.29.0"
futures = "0.3.31"
log = "0.4.28"
log4rs = "1.4.0"
ratatui = "0.29.0"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
tui-textarea = "0.7.0"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
anyhow = "1.0.100"
dirs = "6.0.0"
