[workspace]
resolver = "3"
members = ["chat_client", "chat_lib", "chat_server"]

[workspace.lints.clippy]
unwrap_used = "deny"
needless_match = "deny"
redundant_pattern = "deny"

[profile.release]
opt-level = 3
codegen-units = 1
