[package]
name = "chat_lib"
version = "0.1.0"
edition = "2024"
authors = ["Krickij LÃ¡szlo <krickijlaszlo@gmail.com>"]
description = """
Library for chat
"""

[lints]
workspace = true

[features]
default = []
ws_message = ["dep:rocket_ws"]
ratatui_span = ["dep:ratatui"]

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
semver = { workspace = true }

names = "0.14.0"
ratatui = { version = "0.30.0", optional = true }
rocket_ws = { version = "0.1.1", optional = true }
serde_json = "1.0.149"
