[package]
name = "chat_lib"
version = "0.1.0"
edition = "2024"
authors = ["Krickij LÃ¡szlo <krickijlaszlo@gmail.com>"]
description = """
Library for chat
"""

[lints]
workspace = true

[features]
default = []
ws_message = ["dep:rocket_ws"]
ratatui_span = ["dep:ratatui"]

[dependencies]
names = "0.14.0"
ratatui = { version = "0.29.0", optional = true }
rocket_ws = { version = "0.1.1", optional = true }
semver = "1.0.27"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["sync"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
