[package]
name = "chat_server"
version = "0.1.0"
edition = "2024"
authors = ["Krickij LÃ¡szlo <krickijlaszlo@gmail.com>"]
description = """
A chat server
"""

[lints]
workspace = true


[dependencies]
chat_lib = { path = "../chat_lib", features = ["ws_message"] }

anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
semver = { workspace = true }

dirs = "6.0.0"
log4rs = { version = "1.4.0", features = ["all_components"] }
names = "0.14.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_ws = { version = "0.1.1", features = ["tungstenite"] }
rustrict = "0.7.37"
tokio-tungstenite = "0.28.0"
