[package]
name = "chat_server"
version = "0.1.0"
edition = "2024"
authors = ["Krickij LÃ¡szlo <krickijlaszlo@gmail.com>"]
description = """
A chat server
"""

[lints]
workspace = true

[dependencies]
chat_lib = { path = "../chat_lib", features = ["ws_message"] }

anyhow = "1.0.100"
dirs = "6.0.0"
log = "0.4.29"
log4rs = { version = "1.4.0", features = ["all_components"] }
names = "0.14.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_ws = { version = "0.1.1", features = ["tungstenite"] }
rustrict = "0.7.37"
thiserror = "2.0.17"
tokio = "1.48.0"
tokio-tungstenite = "0.28.0"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
semver = { version = "1.0.27", features = ["serde"] }
